run:
  go: '1.24'
  timeout: 5m
linters-settings:
  govet:
    enable-all: true
linters:
  enable:
    - govet
    - ineffassign
    - errcheck
    - gosimple
    - staticcheck
    - typecheck
    - unused
